-- todo: emergency use

SET search_path to :schema;

CREATE TABLE state (
    state int primary key,
    name text,
    fips char(2)
);

CREATE TABLE accident (
    state integer,
    st_case integer PRIMARY KEY,
    ve_total integer,
    ve_forms integer,
    pvh_invl integer,
    peds integer,
    pernotmvit integer,
    permvit integer,
    persons integer,
    county integer,
    city integer,
    day integer,
    month integer,
    year integer,
    day_week integer,
    hour integer,
    minute integer,
    nhs integer,
    rur_urb integer,
    func_sys integer,
    rd_owner integer,
    route integer,
    tway_id text,
    tway_id2 text,
    milept integer,
    latitude double precision,
    longitud double precision,
    sp_jur integer,
    harm_ev integer,
    man_coll integer,
    reljct1 integer,
    reljct2 integer,
    typ_int integer,
    wrk_zone integer,
    rel_road integer,
    lgt_cond integer,
    weather1 integer,
    weather2 integer,
    weather integer,
    sch_bus integer,
    rail text,
    not_hour integer,
    not_min integer,
    arr_hour integer,
    arr_min integer,
    hosp_hr integer,
    hosp_mn integer,
    cf1 integer,
    cf2 integer,
    cf3 integer,
    fatals integer,
    drunk_dr integer
);

CREATE TABLE cevent (
    state integer,
    st_case integer,
    eventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint cevent_pk primary key (st_case, eventnum)
);

CREATE TABLE damage (
    state integer,
    st_case integer,
    veh_no integer,
    mdareas integer
);

CREATE TABLE distract (
    state integer,
    st_case integer,
    veh_no integer,
    mdrdstrd integer
);

CREATE TABLE drimpair (
    state integer,
    st_case integer,
    veh_no integer,
    drimpair integer
);

CREATE TABLE factor (
    state integer,
    st_case integer,
    veh_no integer,
    mfactor integer
);

CREATE TABLE maneuver (
    state integer,
    st_case integer,
    veh_no integer,
    mdrmanav integer
);

CREATE TABLE nmcrash (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mtm_crsh integer
);

CREATE TABLE nmimpair (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmimpair integer
);

CREATE TABLE nmprior (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    mpr_act integer
);

CREATE TABLE parkwork (
    state integer,
    st_case integer,
    veh_no integer,
    pve_forms integer,
    pnumoccs integer,
    pday integer,
    pmonth integer,
    phour integer,
    pminute integer,
    pharm_ev integer,
    pman_coll integer,
    ptype integer,
    phit_run integer,
    preg_stat integer,
    powner integer,
    pmake integer,
    pmodel integer,
    pmak_mod integer,
    pbodytyp integer,
    pmodyear integer,
    pvin text,
    pvin_1 text,
    pvin_2 text,
    pvin_3 text,
    pvin_4 text,
    pvin_5 text,
    pvin_6 text,
    pvin_7 text,
    pvin_8 text,
    pvin_9 text,
    pvin_10 text,
    pvin_11 text,
    pvin_12 text,
    ptrailer integer,
    pmcarr_i1 text,
    pmcarr_i2 text,
    pmcarr_id text,
    pgvwr integer,
    pv_config integer,
    pcargtyp integer,
    phaz_inv integer,
    phazplac integer,
    phaz_id integer,
    phaz_cno integer,
    phaz_rel integer,
    pbus_use integer,
    psp_use integer,
    pem_use integer,
    punderide integer,
    pimpact1 integer,
    pveh_sev integer,
    ptowed integer,
    pm_harm integer,
    pveh_sc1 integer,
    pveh_sc2 integer,
    pfire integer,
    pdeaths integer,
    ptrlr1vin text,
    ptrlr2vin text,
    ptrlr3vin text,
    constraint parkwork_pk primary key (st_case, veh_no)
);

CREATE TABLE pbtype (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    pbptype integer,
    pbage integer,
    pbsex integer,
    pbcwalk integer,
    pbswalk integer,
    pbszone integer,
    pedctype integer,
    bikectype integer,
    pedloc integer,
    bikeloc integer,
    pedpos integer,
    bikepos integer,
    peddir integer,
    bikedir integer,
    motdir integer,
    motman integer,
    pedleg integer,
    pedsnr text,
    pedcgp integer,
    bikecgp integer,
    constraint pbtype_pk primary key (st_case, per_no)
);

CREATE TABLE person (
    state integer,
    st_case integer,
    ve_forms integer,
    veh_no integer,
    per_no integer,
    str_veh integer,
    county integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    rur_urb integer,
    func_sys integer,
    harm_ev integer,
    man_coll integer,
    sch_bus integer,
    make integer,
    mak_mod integer,
    body_typ integer,
    mod_year integer,
    tow_veh integer,
    spec_use integer,
    emer_use integer,
    rollover integer,
    impact1 integer,
    fire_exp integer,
    age integer,
    sex integer,
    per_typ integer,
    inj_sev integer,
    seat_pos integer,
    rest_use integer,
    rest_mis integer,
    air_bag integer,
    ejection integer,
    ej_path integer,
    extricat integer,
    drinking integer,
    alc_det integer,
    alc_status integer,
    atst_typ integer,
    alc_res integer,
    drugs integer,
    drug_det integer,
    dstatus integer,
    drugtst1 integer,
    drugtst2 integer,
    drugtst3 integer,
    drugres1 integer,
    drugres2 integer,
    drugres3 integer,
    hospital integer,
    doa integer,
    death_da integer,
    death_mo integer,
    death_yr integer,
    death_hr integer,
    death_mn integer,
    death_tm integer,
    lag_hrs integer,
    lag_mins integer,
    p_sf1 integer,
    p_sf2 integer,
    p_sf3 integer,
    work_inj integer,
    hispanic integer ,
    race integer,
    location integer,
    constraint person_pk primary key (st_case, veh_no, per_no)
);

CREATE TABLE safetyeq (
    state integer,
    st_case integer,
    veh_no integer,
    per_no integer,
    nmhelmet integer,
    nmpropad integer,
    nmothpro integer,
    nmrefclo integer,
    nmlight integer,
    nmothpre integer
);

CREATE TABLE vehicle (
    state integer,
    st_case integer,
    veh_no integer,
    ve_forms integer,
    numoccs integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    harm_ev integer,
    man_coll integer,
    unittype integer,
    hit_run integer,
    reg_stat integer,
    owner integer,
    make integer,
    model integer,
    mak_mod integer,
    body_typ integer,
    mod_year integer,
    vin text,
    vin_1 text,
    vin_2 text,
    vin_3 text,
    vin_4 text,
    vin_5 text,
    vin_6 text,
    vin_7 text,
    vin_8 text,
    vin_9 text,
    vin_10 text,
    vin_11 text,
    vin_12 text,
    tow_veh integer,
    j_knife integer,
    mcarr_i1 integer,
    mcarr_i2 text,
    mcarr_id text,
    gvwr integer,
    v_config integer,
    cargo_bt integer,
    haz_inv integer,
    haz_plac integer,
    haz_id integer,
    haz_cno integer,
    haz_rel integer,
    bus_use integer,
    spec_use integer,
    emer_use integer,
    trav_sp integer,
    underide integer,
    rollover integer,
    rolinloc integer,
    impact1 integer,
    deformed integer,
    towed integer,
    m_harm integer,
    veh_sc1 integer,
    veh_sc2 integer,
    fire_exp integer,
    dr_pres integer,
    l_state integer,
    dr_zip text,
    l_status integer,
    l_type integer,
    cdl_stat integer,
    l_endors integer,
    l_compl integer,
    l_restri integer,
    dr_hgt integer,
    dr_wgt integer,
    prev_acc integer,
    prev_sus integer,
    prev_sus1 integer,
    prev_sus2 integer,
    prev_sus3 integer,
    prev_dwi integer,
    prev_spd integer,
    prev_oth integer,
    first_mo integer,
    first_yr integer,
    last_mo integer,
    last_yr integer,
    speedrel integer,
    dr_sf1 integer,
    dr_sf2 integer,
    dr_sf3 integer,
    dr_sf4 integer,
    vtrafway integer,
    vnum_lan integer,
    vspd_lim integer,
    valign integer,
    vprofile integer,
    vpavetyp integer,
    vsurcond integer,
    vtrafcon integer,
    vtcont_f integer,
    p_crash1 integer,
    p_crash2 integer,
    p_crash3 integer,
    pcrash4 integer,
    pcrash5 integer,
    acc_type integer,
    trlr1vin text,
    trlr2vin text,
    trlr3vin text,
    deaths integer,
    dr_drink integer,
    constraint vehicle_pk primary key (st_case, veh_no)
);

CREATE TABLE vevent (
    state integer,
    st_case integer,
    eventnum integer,
    veh_no integer,
    veventnum integer,
    vnumber1 integer,
    aoi1 integer,
    soe integer,
    vnumber2 integer,
    aoi2 integer,
    constraint vevent_pk primary key (st_case, veh_no, eventnum)
);

CREATE TABLE vindecode (
    state integer,
    st_case integer,
    veh_no integer,
    ncicmake text,
    vinyear integer,
    vehtype text,
    vehtype_t text,
    vinmake_t text,
    vinmodel_t text,
    vintrim_t text,
    vintrim1_t text,
    vintrim2_t text,
    vintrim3_t text,
    vintrim4_t text,
    bodystyl text,
    bodystyl_t text,
    doors integer,
    wheels integer,
    drivwhls integer,
    mfg text,
    mfg_t text,
    displci integer,
    displcc integer,
    cylndrs text,
    cycles integer,
    fuel text,
    fuel_t text,
    fuelinj text,
    fuelinj_t text,
    carbtype text,
    carbtype_t text,
    carbbrls text,
    gvwrange integer,
    gvwrange_t text,
    whlbsh double precision,
    whlblg double precision,
    tiredesc_f text,
    psi_f integer,
    tiresz_f text,
    tiresz_f_t text,
    tiredesc_r text,
    psi_r integer,
    rearsize text,
    rearsize_t text,
    tonrating text,
    shipweight integer,
    msrp integer,
    drivetyp text,
    drivetyp_t text,
    salectry text,
    salectry_t text,
    abs text,
    abs_t text,
    security text,
    security_t text,
    drl text,
    drl_t text,
    rstrnt text,
    rstrnt_t text,
    tkcab text,
    tkcab_t text,
    tkaxlef text,
    tkaxlef_t text,
    tkaxler text,
    tkaxler_t text,
    tkbrak text,
    tkbrak_t text,
    engmfg text,
    engmfg_t text,
    engmodel text,
    tkduty text,
    tkduty_t text,
    tkbedl text,
    tkbedl_t text,
    segmnt text,
    segmnt_t text,
    plant text,
    plntctry_t text,
    plntcity text,
    plntctry text,
    plntstat text,
    plntstat_t text,
    origin text,
    origin_t text,
    dispclmt double precision,
    blocktype text,
    enghead text,
    enghead_t text,
    vlvclndr integer,
    vlvtotal integer,
    engvincd text,
    incomplt boolean,
    battyp text,
    battyp_t text,
    batkwrtg text,
    batvolt double precision,
    supchrgr text,
    supchrgr_t text,
    turbo text,
    turbo_t text,
    engvvt text,
    mcyusage text,
    mcyusage_t text,
    constraint vindecode_pk primary key (st_case, veh_no)
);

CREATE TABLE violatn (
    state integer,
    st_case integer,
    veh_no integer,
    mviolatn integer
);

CREATE TABLE vision (
    state integer,
    st_case integer,
    veh_no integer,
    mvisobsc integer
);

CREATE TABLE vsoe (
    state integer,
    st_case integer,
    veh_no integer,
    veventnum integer,
    soe integer,
    aoi integer,
    constraint vsoe_pk primary key (st_case, veh_no, veventnum)
);
