-- todo: emergency use

SET search_path to :schema;

CREATE TABLE IF NOT EXISTS state (
    state int primary key,
    name text,
    fips char(2)
);

CREATE TABLE IF NOT EXISTS accident (
    state integer references state (state),
    st_case integer PRIMARY KEY,
    ve_total integer,
    ve_forms integer,
    pvh_invl integer,
    peds integer,
    pernotmvit integer,
    permvit integer,
    persons integer,
    county integer,
    city integer,
    day integer,
    month integer,
    year integer,
    day_week integer,
    hour integer,
    minute integer,
    nhs integer,
    rur_urb integer references rural_urban (rur_urb),
    func_sys integer references functional_system (func_sys),
    rd_owner integer references road_owner (rd_owner),
    route integer references route (route),
    tway_id text,
    tway_id2 text,
    milept integer,
    latitude double precision,
    longitud double precision,
    sp_jur integer references special_jurisdiction (sp_jur),
    harm_ev integer references harmful_event (harm_ev),
    man_coll integer references manner_of_collision (man_coll),
    reljct1 integer,
    reljct2 integer,
    typ_int integer,
    wrk_zone integer,
    rel_road integer references relation_to_road (rel_road),
    lgt_cond integer references light_condition (lgt_cond),
    weather1 integer references atmospheric_condition (weather),
    weather2 integer references atmospheric_condition (weather),
    weather integer references atmospheric_condition (weather),
    sch_bus integer,
    rail text,
    not_hour integer,
    not_min integer,
    arr_hour integer,
    arr_min integer,
    hosp_hr integer,
    hosp_min integer,
    cf1 integer references related_factors_crash (cf),
    cf2 integer references related_factors_crash (cf),
    cf3 integer references related_factors_crash (cf),
    fatals integer,
    drunk_dr integer
);

CREATE TABLE cevent (
    state integer references state (state),
    st_case integer,
    eventnum integer,
    vnumber1 integer,
    aoi1 integer references area_of_impact (aoi),
    soe integer references sequence_events (soe),
    vnumber2 integer,
    aoi2 integer references area_of_impact (aoi),
    constraint cevent_pk primary key (st_case, eventnum)
);

CREATE TABLE damage (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mdareas integer references damaged_area (mdareas)
);
CREATE INDEX IF NOT EXISTS damage_idx
    ON damage (st_case, veh_no);

CREATE TABLE distract (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mdrdstrd integer references driver_distracted (mdrdstrd)
);
CREATE INDEX IF NOT EXISTS distract_idx
    ON distract (st_case, veh_no);

CREATE TABLE drimpair (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    drimpair integer references impairment (impair)
);
CREATE INDEX IF NOT EXISTS drimpair_idx
    ON drimpair (st_case, veh_no);

CREATE TABLE factor (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mfactor integer references motor_vehicle_factor (mfactor)
);
CREATE INDEX IF NOT EXISTS factor_idx
    ON factor (st_case, veh_no);

CREATE TABLE maneuver (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mdrmanav integer references driver_maneuver (mdrmanav)
);
CREATE INDEX IF NOT EXISTS maneuver_idx
    ON maneuver (st_case, veh_no);

CREATE TABLE nmcrash (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    per_no integer,
    mtm_crsh integer references nonmotorist_contributing (mtm_crsh)
);
CREATE INDEX IF NOT EXISTS nmcrash_idx
    ON nmcrash (st_case, veh_no, per_no);

CREATE TABLE nmimpair (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    per_no integer,
    nmimpair integer references impairment (impair)
);
CREATE INDEX IF NOT EXISTS nmimpair_idx
    ON nmimpair (st_case, veh_no, per_no);

CREATE TABLE nmprior (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    per_no integer,
    mpr_act integer references nonmotorist_action (mpr_act)
);
CREATE INDEX IF NOT EXISTS nmprior_idx
    ON nmprior (st_case, veh_no, per_no);

CREATE TABLE parkwork (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    pve_forms integer,
    pnumoccs integer,
    pday integer,
    pmonth integer,
    phour integer,
    pminute integer,
    pharm_ev integer,
    pman_coll integer references manner_of_collision (man_coll),
    ptype integer,
    phit_run integer references hit_run (hit_run),
    preg_stat integer,
    powner integer references vehicle_owner (owner),
    pmake integer references vehicle_make (make),
    pmodel integer,
    pmak_mod integer,
    pbodytyp integer references body_type (body_typ),
    pmodyear integer,
    pvin text,
    pvin_1 text,
    pvin_2 text,
    pvin_3 text,
    pvin_4 text,
    pvin_5 text,
    pvin_6 text,
    pvin_7 text,
    pvin_8 text,
    pvin_9 text,
    pvin_10 text,
    pvin_11 text,
    pvin_12 text,
    ptrailer integer,
    pmcarr_i1 text,
    pmcarr_i2 text,
    pmcarr_id text,
    pgvwr integer,
    pv_config integer references vehicle_config (v_config),
    pcargtyp integer,
    phaz_inv integer,
    phazplac integer,
    phaz_id integer,
    phaz_cno integer references hazardous_material_class (haz_cno),
    phaz_rel integer,
    pbus_use integer references bus_use (bus_use),
    psp_use integer references special_use (spec_use),
    pem_use integer references emergency_use (emer_use),
    punderide integer,
    pimpact1 integer references area_of_impact (aoi),
    pveh_sev integer,
    ptowed integer,
    pm_harm integer references harmful_event (harm_ev),
    pveh_sc1 integer references related_factors_vehicle (sc),
    pveh_sc2 integer references related_factors_vehicle (sc),
    pfire integer,
    pdeaths integer,
    ptrlr1vin text,
    ptrlr2vin text,
    ptrlr3vin text,
    constraint parkwork_pk primary key (st_case, veh_no)
);

CREATE TABLE pbtype (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    per_no integer,
    pbptype integer references person_type (per_typ),
    pbage integer,
    pbsex integer references sex (sex),
    pbcwalk integer,
    pbswalk integer,
    pbszone integer,
    pedctype integer references ped_crash_type (pedctype),
    bikectype integer references bike_crash_type (bikectype),
    pedloc integer references ped_location (pedloc),
    bikeloc integer references bike_location (bikeloc),
    pedpos integer references ped_position (pedpos),
    bikepos integer references bike_position (bikepos),
    peddir integer,
    bikedir integer,
    motdir integer,
    motman integer,
    pedleg integer,
    pedsnr text,
    pedcgp integer references crash_group_pedestrian (pedcgp),
    bikecgp integer references crash_group_bike (bikecgp),
    constraint pbtype_pk primary key (st_case, per_no)
);

CREATE TABLE person (
    state integer references state (state),
    st_case integer references accident (st_case),
    ve_forms integer,
    veh_no integer,
    per_no integer,
    str_veh integer,
    county integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    rur_urb integer references rural_urban (rur_urb),
    func_sys integer,
    harm_ev integer,
    man_coll integer references manner_of_collision (man_coll),
    sch_bus integer,
    make integer references vehicle_make (make),
    mak_mod integer,
    body_typ integer references body_type (body_typ),
    mod_year integer,
    tow_veh integer references trailing_vehicle (tow_veh),
    spec_use integer references special_use (spec_use),
    emer_use integer references emergency_use (emer_use),
    rollover integer,
    impact1 integer references area_of_impact (aoi),
    fire_exp integer,
    age integer,
    sex integer references sex (sex),
    per_typ integer references person_type (per_typ),
    inj_sev integer references injury_severity (inj_sev),
    seat_pos integer references seating_position (seat_pos),
    rest_use integer,
    rest_mis integer,
    air_bag integer references air_bag (air_bag),
    ejection integer references ejection (ejection),
    ej_path integer references ejection_path (ej_path),
    extricat integer,
    drinking integer,
    alc_det integer references method_alc_det (alc_det),
    alc_status integer references alc_test (alc_status),
    atst_typ integer,
    alc_res integer,
    drugs integer,
    drug_det integer,
    dstatus integer,
    drugtst1 integer,
    drugtst2 integer,
    drugtst3 integer,
    drugres1 integer references drug_test_result (drugres),
    drugres2 integer references drug_test_result (drugres),
    drugres3 integer references drug_test_result (drugres),
    hospital integer references transported_treatment (hospital),
    doa integer,
    death_da integer,
    death_mo integer,
    death_yr integer,
    death_hr integer,
    death_mn integer,
    death_tm integer,
    lag_hrs integer,
    lag_mins integer,
    p_sf1 integer references related_factors_person (p_sf),
    p_sf2 integer references related_factors_person (p_sf),
    p_sf3 integer references related_factors_person (p_sf),
    work_inj integer,
    hispanic integer  references hispanic_origin (hispanic),
    race integer references race (race),
    location integer references location (location),
    constraint person_pk primary key (st_case, veh_no, per_no)
);

CREATE TABLE safetyeq (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    per_no integer,
    msafeqmt integer references safety_equipment (msafeqmt)
);
CREATE INDEX IF NOT EXISTS safetyeq_idx
    ON safetyeq (st_case, veh_no, per_no);

CREATE TABLE vehicle (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    ve_forms integer,
    numoccs integer,
    day integer,
    month integer,
    hour integer,
    minute integer,
    harm_ev integer references harmful_event (harm_ev),
    man_coll integer references manner_of_collision (man_coll),
    unittype integer,
    hit_run integer references hit_run (hit_run),
    reg_stat integer,
    owner integer references vehicle_owner (owner),
    make integer references vehicle_make (make),
    model integer,
    mak_mod integer,
    body_typ integer references body_type (body_typ),
    mod_year integer,
    vin text,
    vin_1 text,
    vin_2 text,
    vin_3 text,
    vin_4 text,
    vin_5 text,
    vin_6 text,
    vin_7 text,
    vin_8 text,
    vin_9 text,
    vin_10 text,
    vin_11 text,
    vin_12 text,
    tow_veh integer references trailing_vehicle (tow_veh),
    j_knife integer,
    mcarr_i1 integer,
    mcarr_i2 text,
    mcarr_id text,
    gvwr integer,
    v_config integer references vehicle_config (v_config),
    cargo_bt integer references cargo_body_type (cargo_bt),
    haz_inv integer,
    haz_plac integer,
    haz_id integer,
    haz_cno integer references hazardous_material_class (haz_cno),
    haz_rel integer,
    bus_use integer references bus_use (bus_use),
    spec_use integer references special_use (spec_use),
    emer_use integer references emergency_use (emer_use),
    trav_sp integer,
    underide integer,
    rollover integer,
    rolinloc integer,
    impact1 integer,
    deformed integer references damage_extent (deformed),
    towed integer,
    m_harm integer references harmful_event (harm_ev),
    veh_sc1 integer,
    veh_sc2 integer,
    fire_exp integer,
    dr_pres integer,
    l_state integer references state (state),
    dr_zip text,
    l_status integer,
    l_type integer,
    cdl_stat integer,
    l_endors integer,
    l_compl integer,
    l_restri integer,
    dr_hgt integer,
    dr_wgt integer,
    prev_acc integer,
    prev_sus integer,
    prev_dwi integer,
    prev_spd integer,
    prev_oth integer,
    first_mo integer,
    first_yr integer,
    last_mo integer,
    last_yr integer,
    speedrel integer references speeding (speedrel),
    dr_sf1 integer references related_factors_driver (dr_sf),
    dr_sf2 integer references related_factors_driver (dr_sf),
    dr_sf3 integer references related_factors_driver (dr_sf),
    dr_sf4 integer references related_factors_driver (dr_sf),
    vtrafway integer references trafficway (vtrafway),
    vnum_lan integer,
    vspd_lim integer,
    valign integer,
    vprofile integer,
    vpavetyp integer,
    vsurcond integer references roadway_surface (vsurcond),
    vtrafcon integer,
    vtcont_f integer,
    p_crash1 integer references pre_event_movement (p_crash1),
    p_crash2 integer references critical_precrash_event (p_crash2),
    p_crash3 integer references attempted_avoidance (p_crash3),
    pcrash4 integer,
    pcrash5 integer,
    acc_type integer references accident_type (acc_type),
    trlr1vin text,
    trlr2vin text,
    trlr3vin text,
    deaths integer,
    dr_drink integer,
    constraint vehicle_pk primary key (st_case, veh_no)
);

CREATE TABLE vevent (
    state integer references state (state),
    st_case integer references accident (st_case),
    eventnum integer,
    veh_no integer,
    veventnum integer,
    vnumber1 integer,
    aoi1 integer references area_of_impact (aoi),
    soe integer references sequence_events (soe),
    vnumber2 integer,
    aoi2 integer references area_of_impact (aoi),
    constraint vevent_pk primary key (st_case, veh_no, eventnum)
);

CREATE TABLE vindecode (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    ncicmake text,
    vinyear integer,
    vehtype text,
    vehtype_t text,
    vinmake_t text,
    vinmodel_t text,
    vintrim_t text,
    vintrim1_t text,
    vintrim2_t text,
    vintrim3_t text,
    vintrim4_t text,
    bodystyl text,
    bodystyl_t text,
    doors integer,
    wheels integer,
    drivwhls integer,
    mfg text,
    mfg_t text,
    displci integer,
    displcc integer,
    cylndrs text,
    cycles integer,
    fuel text,
    fuel_t text,
    fuelinj text,
    fuelinj_t text,
    carbtype text,
    carbtype_t text,
    carbbrls text,
    gvwrange integer,
    gvwrange_t text,
    whlbsh double precision,
    whlblg double precision,
    tiredesc_f text,
    psi_f integer,
    tiresz_f text,
    tiresz_f_t text,
    tiredesc_r text,
    psi_r integer,
    rearsize integer,
    rearsize_t text,
    tonrating text,
    shipweight integer,
    msrp integer,
    drivetyp text,
    drivetyp_t text,
    salectry text,
    salectry_t text,
    abs text,
    abs_t text,
    security text,
    security_t text,
    drl text,
    drl_t text,
    rstrnt text,
    rstrnt_t text,
    tkcab text,
    tkcab_t text,
    tkaxlef text,
    tkaxlef_t text,
    tkaxler text,
    tkaxler_t text,
    tkbrak text,
    tkbrak_t text,
    engmfg text,
    engmfg_t text,
    engmodel text,
    tkduty text,
    tkduty_t text,
    tkbedl text,
    tkbedl_t text,
    segmnt text,
    segmnt_t text,
    plant text,
    plntctry_t text,
    plntcity text,
    plntctry text,
    plntstat text,
    plntstat_t text,
    origin text,
    origin_t text,
    dispclmt double precision,
    blocktype text,
    enghead text,
    enghead_t text,
    vlvclndr integer,
    vlvtotal integer,
    engvincd text,
    incomplt boolean,
    battyp text,
    battyp_t text,
    batkwrtg text,
    batvolt double precision,
    supchrgr text,
    supchrgr_t text,
    turbo text,
    turbo_t text,
    engvvt text,
    mcyusage text,
    mcyusage_t text,
    constraint vindecode_pk primary key (st_case, veh_no)
);

CREATE TABLE violatn (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mviolatn integer references violations_charged (mviolatn)
);
CREATE INDEX IF NOT EXISTS violatn_idx
    ON violatn (st_case, veh_no);

CREATE TABLE vision (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    mvisobsc integer references vision_obscured (mvisobsc)
);
CREATE INDEX IF NOT EXISTS vision_idx
    ON vision (st_case, veh_no);

CREATE TABLE vsoe (
    state integer references state (state),
    st_case integer references accident (st_case),
    veh_no integer,
    veventnum integer,
    soe integer references sequence_events (soe),
    aoi integer references area_of_impact (aoi),
    constraint vsoe_pk primary key (st_case, veh_no, veventnum)
);
